apiVersion: apps/v1
kind: Deployment
metadata:
  name: brightson-store
spec:
  replicas: 1  # Reduce to 1 replica for testing
  selector:
    matchLabels:
      app: brightson-store
  template:
    metadata:
      labels:
        app: brightson-store
    spec:
      containers:
      - name: brightson-store
        image: brightson-store:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "BrightsonStoreApp.settings"
        - name: DJANGO_DEBUG
          value: "True"
        - name: DJANGO_ALLOWED_HOSTS
          value: "*,localhost,127.0.0.1,0.0.0.0,10.244.0.18,192.168.49.2"