apiVersion: v1
kind: Service
metadata:
  name: brightson-store-service
spec:
  type: NodePort
  selector:
    app: brightson-store
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000  # This will make the app accessible on port 30000